# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageType.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11MessageType.proto\"\x12\n\x03\x45rr\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t\"U\n\x03Put\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\t\x12&\n\x10\x63onsistencylevel\x18\x04 \x01(\x0e\x32\x0c.Consistency\"F\n\x03Get\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\r\x12&\n\x10\x63onsistencylevel\x18\x03 \x01(\x0e\x32\x0c.Consistency\"6\n\x0bPutResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\"z\n\x0eGetResponseLst\x12-\n\x08response\x18\x01 \x03(\x0b\x32\x1b.GetResponseLst.GetResponse\x1a\x39\n\x0bGetResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"\x99\x01\n\x03Msg\x12\x13\n\x03Get\x18\x01 \x01(\x0b\x32\x04.GetH\x00\x12\x13\n\x03Put\x18\x02 \x01(\x0b\x32\x04.PutH\x00\x12\"\n\nPutRequest\x18\x03 \x01(\x0b\x32\x0c.PutResponseH\x00\x12(\n\rGetRequestLst\x18\x04 \x01(\x0b\x32\x0f.GetResponseLstH\x00\x12\x13\n\x03\x65rr\x18\x05 \x01(\x0b\x32\x04.ErrH\x00\x42\x05\n\x03msg*\"\n\x0b\x43onsistency\x12\x07\n\x03ONE\x10\x00\x12\n\n\x06QUORUM\x10\x01\x62\x06proto3')
)

_CONSISTENCY = _descriptor.EnumDescriptor(
  name='Consistency',
  full_name='Consistency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUORUM', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=536,
  serialized_end=570,
)
_sym_db.RegisterEnumDescriptor(_CONSISTENCY)

Consistency = enum_type_wrapper.EnumTypeWrapper(_CONSISTENCY)
ONE = 0
QUORUM = 1



_ERR = _descriptor.Descriptor(
  name='Err',
  full_name='Err',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='Err.err', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=39,
)


_PUT = _descriptor.Descriptor(
  name='Put',
  full_name='Put',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Put.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='Put.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Put.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consistencylevel', full_name='Put.consistencylevel', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=126,
)


_GET = _descriptor.Descriptor(
  name='Get',
  full_name='Get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Get.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='Get.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consistencylevel', full_name='Get.consistencylevel', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=198,
)


_PUTRESPONSE = _descriptor.Descriptor(
  name='PutResponse',
  full_name='PutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PutResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='PutResponse.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='PutResponse.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=254,
)


_GETRESPONSELST_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='GetResponseLst.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetResponseLst.GetResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='GetResponseLst.GetResponse.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='GetResponseLst.GetResponse.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=378,
)

_GETRESPONSELST = _descriptor.Descriptor(
  name='GetResponseLst',
  full_name='GetResponseLst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='GetResponseLst.response', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETRESPONSELST_GETRESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=378,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Get', full_name='Msg.Get', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Put', full_name='Msg.Put', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PutRequest', full_name='Msg.PutRequest', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GetRequestLst', full_name='Msg.GetRequestLst', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='Msg.err', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='Msg.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=381,
  serialized_end=534,
)

_PUT.fields_by_name['consistencylevel'].enum_type = _CONSISTENCY
_GET.fields_by_name['consistencylevel'].enum_type = _CONSISTENCY
_GETRESPONSELST_GETRESPONSE.containing_type = _GETRESPONSELST
_GETRESPONSELST.fields_by_name['response'].message_type = _GETRESPONSELST_GETRESPONSE
_MSG.fields_by_name['Get'].message_type = _GET
_MSG.fields_by_name['Put'].message_type = _PUT
_MSG.fields_by_name['PutRequest'].message_type = _PUTRESPONSE
_MSG.fields_by_name['GetRequestLst'].message_type = _GETRESPONSELST
_MSG.fields_by_name['err'].message_type = _ERR
_MSG.oneofs_by_name['msg'].fields.append(
  _MSG.fields_by_name['Get'])
_MSG.fields_by_name['Get'].containing_oneof = _MSG.oneofs_by_name['msg']
_MSG.oneofs_by_name['msg'].fields.append(
  _MSG.fields_by_name['Put'])
_MSG.fields_by_name['Put'].containing_oneof = _MSG.oneofs_by_name['msg']
_MSG.oneofs_by_name['msg'].fields.append(
  _MSG.fields_by_name['PutRequest'])
_MSG.fields_by_name['PutRequest'].containing_oneof = _MSG.oneofs_by_name['msg']
_MSG.oneofs_by_name['msg'].fields.append(
  _MSG.fields_by_name['GetRequestLst'])
_MSG.fields_by_name['GetRequestLst'].containing_oneof = _MSG.oneofs_by_name['msg']
_MSG.oneofs_by_name['msg'].fields.append(
  _MSG.fields_by_name['err'])
_MSG.fields_by_name['err'].containing_oneof = _MSG.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['Err'] = _ERR
DESCRIPTOR.message_types_by_name['Put'] = _PUT
DESCRIPTOR.message_types_by_name['Get'] = _GET
DESCRIPTOR.message_types_by_name['PutResponse'] = _PUTRESPONSE
DESCRIPTOR.message_types_by_name['GetResponseLst'] = _GETRESPONSELST
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.enum_types_by_name['Consistency'] = _CONSISTENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), dict(
  DESCRIPTOR = _ERR,
  __module__ = 'MessageType_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  ))
_sym_db.RegisterMessage(Err)

Put = _reflection.GeneratedProtocolMessageType('Put', (_message.Message,), dict(
  DESCRIPTOR = _PUT,
  __module__ = 'MessageType_pb2'
  # @@protoc_insertion_point(class_scope:Put)
  ))
_sym_db.RegisterMessage(Put)

Get = _reflection.GeneratedProtocolMessageType('Get', (_message.Message,), dict(
  DESCRIPTOR = _GET,
  __module__ = 'MessageType_pb2'
  # @@protoc_insertion_point(class_scope:Get)
  ))
_sym_db.RegisterMessage(Get)

PutResponse = _reflection.GeneratedProtocolMessageType('PutResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTRESPONSE,
  __module__ = 'MessageType_pb2'
  # @@protoc_insertion_point(class_scope:PutResponse)
  ))
_sym_db.RegisterMessage(PutResponse)

GetResponseLst = _reflection.GeneratedProtocolMessageType('GetResponseLst', (_message.Message,), dict(

  GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), dict(
    DESCRIPTOR = _GETRESPONSELST_GETRESPONSE,
    __module__ = 'MessageType_pb2'
    # @@protoc_insertion_point(class_scope:GetResponseLst.GetResponse)
    ))
  ,
  DESCRIPTOR = _GETRESPONSELST,
  __module__ = 'MessageType_pb2'
  # @@protoc_insertion_point(class_scope:GetResponseLst)
  ))
_sym_db.RegisterMessage(GetResponseLst)
_sym_db.RegisterMessage(GetResponseLst.GetResponse)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'MessageType_pb2'
  # @@protoc_insertion_point(class_scope:Msg)
  ))
_sym_db.RegisterMessage(Msg)


# @@protoc_insertion_point(module_scope)
